replicaCount: 1

image:
  repository: 490457333441.dkr.ecr.us-west-1.amazonaws.com/ebank-backend
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 5000

env:
  NODE_ENV: "production"  # ✅ Added to activate production CORS config
  PORT: "5000"
  MONGO_URI: "mongodb+srv://yogi:Mischief1999@login-app.0e1k1oz.mongodb.net/?retryWrites=true&w=majority&appName=login-app"
  JWT_SECRET: "591320c35c7581e09f4bd7d81153ac2bd9e0abf91f5d223b5862227cc3233cc4e6f1324ab2e35fd0fec36a3c4769d31530b2a18169f772cae26d2d14b010156a"
  JWT_EXPIRE: "1d"
  CORS_DOMAINS: "http://50.18.142.175,http://localhost:3000"
