apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ebank-backend.fullname" . }}-config
data:
  PORT: "{{ .Values.env.PORT }}"
  MONGO_URI: "{{ .Values.env.MONGO_URI }}"
  JWT_SECRET: "{{ .Values.env.JWT_SECRET }}"
  JWT_EXPIRE: "{{ .Values.env.JWT_EXPIRE }}"
  CORS_DOMAINS: "{{ .Values.env.CORS_DOMAINS }}"
