apiVersion: v1
kind: Service
metadata:
  name: {{ include "ebank-backend.fullname" . }}
  annotations:
    alb.ingress.kubernetes.io/backend-protocol: HTTP
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "ebank-backend.name" . }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5000
